### PR TITLE
Add Spectral Noise Reduction

### PR DESCRIPTION
**Pull request by grahamwhaley**
Add a Spectral Noise Reduction filter.
Based on the code from the [UHSDR](https://github.com/df8oe/UHSDR/blob/active-devel/mchf-eclipse/drivers/audio/audio_nr.c) and [Teensy-ConvolutionSDR](https://github.com/DD4WH/Teensy-ConvolutionSDR/wiki/Spectral--noise-reduction).

Components added:
 - filter block code
 - example code
 - UI additions

The code as is works, but there is still a bit more 'watery' background effect than I'd like. If anybody else is familiar with the techniques and code, please feel free to take a look. It is quite conceivable I've missed or messed something up a little and not noticed...

**Note:** This code is under the GNU GPLv3, rather than the MIT license the rest of the OpenAudio Library is under because the original code of both UHSDR and ConvolutionSDR are both GNU GPLv3. We may need to discuss if that is an issue or not. We might want to ask @DD4WH and @df8oe if they have any thoughts on that as well.

/cc @boblark 

Fixes: #12

### CODE REVIEW

**Review by boblark — APPROVED** [review]
Thanks much Graham.  I will be playing with these and will let the KeithSDR group know these are available

**Comment by NickTheVic** [comment]
Thanks very much for doing this Graham. I've got it working! I shall follow the development of this with great interest.

73

Nick
M0NTV

**Comment by grahamwhaley** [comment]
Hey, hi @NickTheVic ! iirc, last time we looked at this you were having trouble getting the spectral code from (DSPHAM)[https://github.com/grahamwhaley/DSPham) to compile - looks like this has helped fix that! Good :-)

If you have any feedback on performance, feel free to drop it here. Right now I think the actual noise reduction works, and the background 'watery' noise can be reduced by altering the Alpha var, but it sounds to my ears like the NR is making the voices a bit 'boomy' and distorted (that might just be the nature of spectral NR....). I have a feeling passing the audio through a suitable filter that reduces either the input or output to just the voice range (300-2800hz or whatever) might help overall.

In my original use case I had a lot of background noise that was fatiguing - and the Spectral made listening to my receiver much more pleasant. It will be interesting to hear how it works out for others in different situations. 

I'm not sure if/when I'll get to re-visit the code. I'd like to but...
 - I have a bunch of things to do right now that will likely preclude much activity from me for a few months
 - I'm more a 'visual' than in-head-math guy. I know that to do justice to the code I need to 'see' the waveforms and what the NR code is doing to them - which would involve constructing some framework, which is quite a bit of effort...

**Comment by NickTheVic** [comment]
Thanks very much Graham!

I must confess that DSP is something of a dark art to me - and one that I'm yet to master!!! I'm afraid I gave up on the DSPHAM code as I just couldn't get it to compile and didn't really know enough to sort out why. However, once I'd sorted out the dependencies for this it compiled straight away and I've been testing it for a day or so. It certainly makes a big difference and I think it stands up remarkably well to the NR in my commercial transceiver and my external BHI speaker. I'll have a play with the Alpha and try some voice range filtering. 

But really great job! I've been waiting for this for ages and I can see me implementing this in my homebrew rigs.

Thanks again.

**Pull request merged**
