### PR TITLE
added a NoiseGate-Effect

### PR DESCRIPTION
**Pull request by max-huster**
Hey everyone, i just spent time and developed a NoiseGate effect. I'd like to contribute to the project.

### CODE REVIEW

**Comment by boblark** [comment]
Hi - Thanks much for the NoiseGate-Effect Class.  This is good timing as I'm collecting/writing blocks that fit into communications systems and this looks to be useful for this sort of thing.  I looked at the .h file and would propose to pull it in.  But first, your example, can we name the example file examples/NoiseGate/NoiseGate.ino ?   It looks to be Arduino compatible except for the file name.  I can change that if it is easier.  Bob Larkin

**Comment by max-huster** [comment]
Hi, i just renamed it. You can merge it :)

**Comment by boblark** [comment]
You are right that there is no full scale in float.  Historically, going 
back to the I16 Teensy Audio Library, a level of + or - 1.0 serves where 
a FS value is needed.  That is the case for this class as well.   
Obviously, one of the feature of using the floats is that nothing much 
bad happens when we go beyond that level.  The exception to all this is 
when one converts back to I16 for I/O.  In that case, as expected, 
0.999969 is32767 and -1.0000 is -32768.

That particular class was from Max Huster, and Max, feel free to add 
anything here.   Bob L

**Comment by max-huster** [comment]
Hey everyone,

looing at my code, the parameter in the method should better be called `db` instead of `dbfs`. 

Also i rechecked the calculation in the setThreshold function with a graphical Calculator:
Screenshot

So if you set up your Noise gate with `setThreshold(-12.0f);` it mutes everything below -12 dB. 

I hope this clarifies the question :)

Kind Regards

Max

**Pull request merged**
