### PR TITLE
Added mixer in float format

### PR DESCRIPTION
**Pull request by patrick-radius**
Added a four channel mixer in float format.

I'm pretty new to ARM and DSP stuff, so i guess it might not be the best/most efficient solution.
However, it works.

### CODE REVIEW

**Comment by chipaudette** [comment]
Wow!  Thanks so much for contributing this! 

May I ask you for a couple of edits before I merge?

1) In your *.h file, please add comments at the top to identify the file, its original creator (you!), and to assign it the MIT license.  For an example, see [AudioEffectGain_F32.h](https://github.com/chipaudette/OpenAudio_ArduinoLibrary/blob/master/AudioEffectGain_F32.h)

2) In your *.h file, in your gain() method, can you remove the +/-127.0 limits on the gain.  Given that this is a floating-point class (as opposed to the original Int16 class), we don't need to worry as much about overflowing.

And then, for your consideration (or for continued discussion), I feel that the default channel gain should be 1.0 not 0.5.  Looking at Paul's original mixer, he's got a bunch of integer math that is hard for me to parse by eye.  Does it all work out to a gain of 1.0 or a gain of 0.5?

If you're willing to make changes (1) and (2) and consider (3), I'll be very, very happy to include your contributions!

Chip

**Comment by patrick-radius** [comment]
Thanks for your reply, i will make the modifications.
I think you're right about the fact there is not so much to worry about overflowing, however, i still think there is a risk of digital clipping, right? But i guess the +/-127.0 limits are too arbitrary for that purpose, so probably are better left out.

By the way, how close do you want to reproduce Paul's original library? Because i also have an Oscillator and Envelope generator in float, but it uses different algorithms. Would you be interested in those?

**Comment by chipaudette** [comment]
Thanks so much!

Regarding closeness to Paul's library, I think that my goal would be to have the input-output behavior be the same, except for things like these artificial limits that were imposed due to the Int16 data type.  

(A second difference is that, for the floating-point library, notional "full scale" is +/-1.0 instead of +/-32768.  One can feel free to exceed +/-1.0 in one's floating-point algorithm, but at the very end of the processing chain, before it gets handed back to the DAC, the floating-point audio data will get truncated at 1.0 so that it can be converted to 32768.)

As for you converting the algorithms, I'd look to see that the inputs-outputs are the same (or similar) so that someone familiar with the original algorithm could easily use the new one (hopefully without consulting any of the documentation).  

So, stuff exposed to the user should be very similar / the same, but stuff under the hood could deviate if it had to.  Does that make any sense?

Thanks again for contributing.  This is great!

Chip

**Comment by chipaudette** [comment]
Oh yeah, and when you create new contributions that involve a new *.h file (like your recent two pull requests), don't forget to add the *.h file to the library's overall header file, [OpenAudio_ArduinoLibrary.h](https://github.com/chipaudette/OpenAudio_ArduinoLibrary/blob/master/OpenAudio_ArduinoLibrary.h).

Chip

**Comment by chipaudette** [comment]
I updated the OpenAudio_ArduinoLibrary.h and I added your class names to keywords.txt.  I also created an example sketch using the mixer and added it to the Examples directory.  Cool!  Now I'm about to do a blog post inspired by your contributions.  Thanks!

**Comment by chipaudette** [comment]
Blog post completed with example code using AudioMixer4_F32.  Example code added to this library.

http://openaudio.blogspot.com/2017/01/received-my-first-pull-request.html

**Pull request merged**
